### ISSUE TITLE
missing autocomplete in bash

### ISSUE THREAD

**Issue by zaoral** [Vauxoo/docker-odoo-image#29] opened 2015-10-19 18:17 UTC
When ruining the container i will like that bash have the auto complete feature when i type a command name

**Current Behavior**
- I type `git check` then press the tab key. nothing happend

**Expected Behavior**
- I type `git check` then press the tab key and the command line shouls show me `git checkout`

**Comment by ruiztulio** [comment] 2015-10-28 19:58
@zaoral Tested in a few containers and seems to be working fine:
![yoytec80](http://i.imgur.com/gvj2QLm.png)

![lodi80](http://i.imgur.com/cc9hIwh.png)

Probably you are working in an older version or a container based in a different image.

**Comment by JulioSerna** [comment] 2015-10-28 20:24
@ruiztulio 
I have the same issue, 
I run the container like this
```b2d run -itP  --name prueba_12 --entrypoint=bash -t vauxoo-prueba_23:8.0```

**Comment by moylop260** [comment] 2015-10-28 20:28
@ruiztulio 
The issue is our image of `shippable`.
Do you know what is the cause of this error?
(If you fixed this recently you will need re-build image in docker-hub manually)

**Comment by ruiztulio** [comment] 2015-10-28 20:47
@moylop260 I'm not the one maintaining shippable image, besides this was fixed a few months ago in 62cefa119af1f8de99902c0b55db97ed703f76e8 , but isn't shippable image building automatically when a PR is merged?

**Comment by moylop260** [comment] 2015-10-29 03:43
Shippable image use your image:
https://github.com/Vauxoo/docker-odoo-image/blob/62cefa119af1f8de99902c0b55db97ed703f76e8/odoo-shippable/Dockerfile#L1
But isn't re-build image if `FROM image` is changed, we need press button rebuild in docker-hub manually :(
I will to push it

**Comment by moylop260** [comment] 2015-10-29 03:46
@JulioSerna  and @zaoral 
Now is building
![building](https://cloud.githubusercontent.com/assets/6644187/10809544/a9d45750-7dc5-11e5-877b-152f14831278.png)

Tomorrow you can execute `docker pull` and test it.

**Closed** 2015-11-05 21:06 UTC

**Comment by moylop260** [comment] 2015-11-05 21:23
Fixed https://github.com/Vauxoo/docker-odoo-image/pull/34
<img width="372" alt="captura de pantalla 2015-11-05 a las 4 22 20 p m" src="https://cloud.githubusercontent.com/assets/6644187/10982128/8e670052-83d9-11e5-86e3-465be150de83.png">
